# Generated by Django 4.2.7 on 2023-11-12 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('timezone_str', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'store',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_utc', models.DateTimeField()),
                ('status', models.CharField(max_length=25)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_status', to='store_app.store')),
            ],
            options={
                'db_table': 'store_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StoreHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('start_time_local', models.TimeField()),
                ('end_time_local', models.TimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_hours', to='store_app.store')),
            ],
            options={
                'db_table': 'store_hours',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StoreFileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('report_url', models.FileField(blank=True, null=True, upload_to='reports')),
                ('report_id', models.CharField(max_length=50, unique=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_status', to='store_app.store')),
            ],
            options={
                'db_table': 'store_file_status',
                'managed': True,
            },
        ),
    ]
