# Generated by Django 4.2.7 on 2023-11-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storehours',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storestatus',
            name='store',
        ),
        migrations.AddField(
            model_name='storehours',
            name='store_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storestatus',
            name='store_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
