# Generated by Django 4.2.7 on 2023-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_remove_storehours_store_remove_storestatus_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storehours',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
